name: Run ast-grep validation rules
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

env:
  GIT_CREDENTIALS: ${{ secrets.ASTGREP_RULES_TOKEN }}

jobs:
  ast-grep-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Checkout Rules Repo
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v4
        with:
          repository: victory-sokolov/astgrep-rules
          token: ${{ secrets.ASTGREP_RULES_TOKEN }}
          ref: main
          path: external-rules
          fetch-depth: 1

      - name: Install ast-grep
        run: npm install -g @ast-grep/cli

      - name: Run Rules
        run: ast-grep scan -c external-rules/sgconfig.yml
